name: wastego
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-210.2.beta <4.0.0'

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  google_sign_in: ^6.1.6
  shared_preferences: ^2.0.8
  firebase_auth: ^4.16.0
  google_sign_in_platform_interface: ^2.4.5
  firebase_core: ^2.24.2
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
